### PR TITLE
fix: Update to GO 1.18 so scan works on new projects

### PR DESCRIPTION
**Pull request by adadkins**
If you run ```gokart scan``` on go 1.18 projects, you get an error: 

```internal error: package "time" without types was imported from "github.com/Omaze/cl-sweeps-api/internal/common"```

We need to have a 1.18 build for gokart for it to work with new go projects

### CODE REVIEW

**Comment by ynsta** [comment]
Would also need this fix.

**Comment by adadkins** [comment]
@isp1r0 @praetorian-harry Hey sorry to ping, just curious if we can merge this so gokart works with new go projects

**Comment by sc-atompower** [comment]
@ynsta @adadkins  the go team recently announced https://go.dev/blog/vuln

**Comment by adadkins** [comment]
@sc-atompower thanks for that, i did not see that announcement. I'm gong to close this PR and switch to using that. Thanks

**Comment by nekochanell** [comment]
> @ynsta @adadkins the go team recently announced https://go.dev/blog/vuln

It's not even the same thing. GoKart is a static code analyser. GoVulnCheck is for dependency vulnerability management. 

This issue should be reopened.

**Comment by adadkins** [comment]
Reopening

**Review by praetorian-thendrickson — APPROVED** [review]
Thanks!

**Comment by praetorian-thendrickson** [comment]
Hey @adadkins thank you for your help with this PR. I updated it slightly, so the current main branch https://github.com/praetorian-inc/gokart/pull/80 should now work.

**Pull request merged**
